services:
  - type: web
    name: avana-backend
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js

  - type: web
    name: avana-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start